CREATE DATABASE DernekYonetimDb
GO
USE DernekYonetimDb
GO
CREATE TABLE Kisi(
	Id INT PRIMARY KEY IDENTITY,
	Ad NVARCHAR(64),
	Soyad NVARCHAR(64),
	Telefon CHAR(11),
	EMail VARCHAR(128)
)
GO
CREATE TABLE Unvan(
	Id INT PRIMARY KEY IDENTITY,
	Tanim NVARCHAR(64) NOT NULL
)
GO
CREATE TABLE Yonetici(
	Id INT PRIMARY KEY IDENTITY,
	KisiId INT FOREIGN KEY REFERENCES Kisi(Id) NOT NULL,
	UnvanId INT FOREIGN KEY REFERENCES Unvan(Id) NOT NULL,
	BaslangicTarihi DATETIME NOT NULL,
	BitisTarihi DATETIME
)
GO
CREATE TABLE Uye(
	Id INT PRIMARY KEY IDENTITY,
	KisiId INT FOREIGN KEY REFERENCES Kisi(Id) NOT NULL,
	UyelikBaslangicTarihi DATE NOT NULL,
	UyelikBitisTarihi DATE,
	AktifMi BIT NOT NULL DEFAULT(1)
)
GO
CREATE TABLE Donem(
	Id INT PRIMARY KEY IDENTITY,
	Ay INT NOT NULL,
	Yil INT NOT NULL,
	Tanim NVARCHAR(32)
)
GO
CREATE TABLE HareketTip(
	Id INT PRIMARY KEY IDENTITY,
	Tanim NVARCHAR(64) NOT NULL
)
GO
CREATE TABLE MaliHareket(
	Id INT PRIMARY KEY IDENTITY,
	KisiId INT FOREIGN KEY REFERENCES Kisi(Id) NOT NULL,
	TipId INT FOREIGN KEY REFERENCES HareketTip(Id) NOT NULL,
	Miktar MONEY NOT NULL DEFAULT(0)
)
GO
CREATE TABLE Aidat(
	Id INT PRIMARY KEY IDENTITY,
	DonemId INT FOREIGN KEY REFERENCES Donem(Id) NOT NULL,
	KisiId INT FOREIGN KEY REFERENCES Kisi(Id) NOT NULL,
	HareketId INT FOREIGN KEY REFERENCES MaliHareket(Id) NOT NULL
)
GO
CREATE TABLE Toplanti(
	Id INT PRIMARY KEY IDENTITY,
	ToplantiTarihi DATETIME NOT NULL,
	Konum NVARCHAR(128)
)
GO
CREATE TABLE TopantiDetay(
	Id INT PRIMARY KEY FOREIGN KEY REFERENCES Toplanti(Id),
	Konu NVARCHAR(128) NOT NULL,
	Notlar NVARCHAR(MAX)
)
GO
CREATE TABLE ToplantiKisi(
	ToplantiId INT FOREIGN KEY REFERENCES Toplanti(Id) NOT NULL,
	KisiId INT FOREIGN KEY REFERENCES Kisi(Id) NOT NULL
)
GO

INSERT INTO Unvan (Tanim) VALUES ('Yönetim Kurulu Baþkaný')
INSERT INTO Unvan (Tanim) VALUES ('Yönetim Kurulu Baþkan Yardýmcýsý')
INSERT INTO Unvan (Tanim) VALUES ('Yönetim Kurulu Üyesi')
INSERT INTO Unvan (Tanim) VALUES ('Genel Sekreter')
INSERT INTO Unvan (Tanim) VALUES ('Muhasebeci')

GO

INSERT INTO HareketTip(Tanim) VALUES ('Aidat')
INSERT INTO HareketTip(Tanim) VALUES ('Baðýþ')
INSERT INTO HareketTip(Tanim) VALUES ('Para Çekme')

GO 

INSERT INTO Donem(Ay,Yil,Tanim)VALUES(1,2019,'Ocak-2019')
INSERT INTO Donem(Ay,Yil,Tanim)VALUES(2,2019,'Þubat-2019')
INSERT INTO Donem(Ay,Yil,Tanim)VALUES(3,2019,'Mart-2019')
INSERT INTO Donem(Ay,Yil,Tanim)VALUES(4,2019,'Nisan-2019')
INSERT INTO Donem(Ay,Yil,Tanim)VALUES(5,2019,'Mayýs-2019')





